### ISSUE TITLE
No connection to server - java.security.NoSuchAlgorithmException

### ISSUE THREAD

**Issue by TheSoulrester** [ichbinbenni/MineConnectAppPublic#11]
I cannot connect to my server with the ios app. while connecting, i am getting this error in my server console:

```
[14:57:50 WARN]: Exception in thread "Thread-64" java.security.NoSuchAlgorithmException: Cannot find any provider supporting AES/GCM/PKCS5Padding
[14:57:50 WARN]:        at java.base/javax.crypto.Cipher.getInstance(Cipher.java:571)
[14:57:50 WARN]:        at utility.EncryptionManager$Companion.aes(EncryptionManager.kt:86)
[14:57:50 WARN]:        at utility.EncryptionManager$Companion.aesDecrypt(EncryptionManager.kt:78)
[14:57:50 WARN]:        at utility.EncryptedStreamBuffer.<init>(EncryptedStreamBuffer.kt:23)
[14:57:50 WARN]:        at tcp.tcpMessageHandler.connectionSetup.AuthTokenHandler.read(AuthTokenHandler.kt:36)
[14:57:50 WARN]:        at tcp.TCPConnectionManager.reading(TCPConnectionManager.kt:90)
[14:57:50 WARN]:        at tcp.TCPConnectionManager.start(TCPConnectionManager.kt:46)
[14:57:50 WARN]:        at tcp.TCPSocketManager$start$1$1$1.invoke(TCPSocketManager.kt:38)
[14:57:50 WARN]:        at tcp.TCPSocketManager$start$1$1$1.invoke(TCPSocketManager.kt:10)
[14:57:50 WARN]:        at kotlin.concurrent.ThreadsKt$thread$thread$1.run(Thread.kt:30)
[14:57:50 WARN]: Caused by: javax.crypto.NoSuchPaddingException: GCM mode must be used with NoPadding
[14:57:50 WARN]:        at java.base/com.sun.crypto.provider.CipherCore.setPadding(CipherCore.java:300)
[14:57:50 WARN]:        at java.base/com.sun.crypto.provider.AESCipher.engineSetPadding(AESCipher.java:221)
[14:57:50 WARN]:        at java.base/javax.crypto.Cipher$Transform.setModePadding(Cipher.java:388)
[14:57:50 WARN]:        at java.base/javax.crypto.Cipher.getInstance(Cipher.java:564)
[14:57:50 WARN]:        ... 9 more
```

I am using the latest papermc build.

**Comment by ichbinbenni** [comment]
Hey, this is an error when using a relatively new Java version.
I am aware of it, but there will be no hotfix, because currently I don't have time for it.

I will post an update here when I release a new version with a fix.

**Comment by blackstormlab** [comment]
any idea of when a new version would be released ? or how we can fix this ourselves ?

**Comment by ichbinbenni** [comment]
You have to downgrade your Java version. I would not recommend it.

No, from the current point I can't say a date. Sorry :/

**Comment by FirbyKirby** [comment]
please let us know if there is anything your users can do to help. With the latest version of Minecraft server requiring Java 16, it's certainly not feasible (and as you said not recommended) to downgrade. Therefore, the app is currently unusable. We certainly like it and depended on it for our server.

**Comment by trebory6** [comment]
@ichbinbenni Hey there! Hope you're doing well.  Just wanted to throw in my own words of support that I'd love to see this project get back off the ground!

Honestly, the app was amazing and I love that it was free, so I'll probably be roasted for putting ideas in your head, but you could seriously charge for this if you wanted to, or put certain features behind a paywall, all if it helps keep up development of this app/plugin going. If I knew more about java I'd offer to help out, but unfortunately I don't. At that point you could probably even hire someone to upkeep it part time. 

Anyways, hope all is well.

**Comment by ver24436** [comment]
Just discovered this App / Plugin. It's exactly what I was looking for, and have yet to find something simular. Disappointed to learn that it doesn't yet support Java 16 as needed for current releases of PaperMC. Hope that this project will resume and this issue can be fixed. Looking forward to the opportunity to try it out with our server sometime soon.

**Comment by pendleton115** [comment]
I have the same problem, was really excited to get this running  but now it looks like it won't be possible :(
